---
- include_role: name=yum-repo

- name: Install dependencies
  yum: name={{ item }} state=present
  loop: "{{ consul.dependencies }}"



- block:
  - name: Stop consul
    service: name=consul state=stopped

  - name: check old db exists
    stat: path=/var/bin/consul
    register: dbpath

  - name: get stopped consul version
    command: "consul -v"
    register: oldversion

  - name: backup old database folder
    command: "cp /var/bin/consul /var/bin/consul_{{ oldversion }}"
    when: dbpath.stat.exists

  - name: move backup file to backup db folder
    command: "mv /etc/consul/backup.snap /var/bin/consul_{{ oldversion }}"

  when: ansible_facts.packages['consul'][0].version is defined

- name: "install consul new version {{ consul.version }}"
  yum: name=consul-{{ consul.version }} state=present

- name: create link for server only in our setup
  file:
    src: /etc/consul/server.json
    dest: /etc/consul/config.json
    state: link

- name: replace with real ip addr
  replace:
    path: /etc/consul/config.json
    regexp: '"advertise_addr" : "IP",'
    replace: '"advertise_addr" : "{{ ansible_default_ipv4.address }}",'

- name: Check consul running
  service: name=consul state=started enabled=true

- name: Creates a cron file under /etc/cron.d to backup db
  cron:
    name: consul backup daily
    weekday: '*'
    minute: "30"
    hour: "0"
    user: root
    job: "consul snapshot save /etc/consul/backup.snap"

- include_role: name=nginx
- include_role: name=sensu-client
- include_role: name=filebeat
